GET http://localhost:3010/api/users 

###
POST http://localhost:3010/api/users
Content-Type: application/json

{
    "email": "ekorre@hotmail.com",
    "password": "snigell",
    "subscribe": true
}

###
PUT http://localhost:3010/api/users
Content-Type: application/json
{
    "_id":"62908c6a3c56a32bf25f7b5d",
    "email": "bertil.andersson@gmail.com",
    "password": "bertil",   
    "subscribe": "false"
}


###
DELETE http://localhost:3010/api/users 
Content-Type: application/json
###
POST http://localhost:3010/api/users/login
Content-Type: application/json

{
    "email": "ekorre@hotmail.com",
    "password": "snigell"
}
